### ISSUE TITLE
Test windows build

### ISSUE THREAD

**Issue by jcfr** [commontk/bzip2#1]
@mrhardisty Would be great if you could test windows build (32 and 64 bit)

Report here which version of Visual Studio you end up using. Merci

**Comment by mrhardisty** [comment]
The Windows builds in 32 and 64bit succeed. The output is below.  Both builds were done with Visual Studio 2013 in Release configuration.

64bit

------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
  Checking Build System
  CMake does not need to re-run because C:/bzip2/CMakeFiles/generate.stamp is up-to-date.
------ Build started: Project: libbz2, Configuration: Release x64 ------
  Building Custom Rule C:/Users/Michael/Documents/Git/bzip2/CMakeLists.txt
  CMake does not need to re-run because C:/bzip2/CMakeFiles/generate.stamp is up-to-date.
  blocksort.c
  huffman.c
  crctable.c
  randtable.c
  compress.c
C:\Users\Michael\Documents\Git\bzip2\compress.c(205): warning C4244: '=' : conversion from '__int64' to 'Int32', possible loss of data
  decompress.c
  bzlib.c
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(997): warning C4267: '=' : conversion from 'size_t' to 'Int32', possible loss of data
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1056): warning C4267: '=' : conversion from 'size_t' to 'Int32', possible loss of data
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1191): warning C4267: '=' : conversion from 'size_t' to 'Int32', possible loss of data
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1417): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1418): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1423): warning C4996: 'setmode': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _setmode. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\io.h(338) : see declaration of 'setmode'
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1423): warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fileno. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(718) : see declaration of 'fileno'
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1425): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(211) : see declaration of 'fopen'
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1431): warning C4996: 'fdopen': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fdopen. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(716) : see declaration of 'fdopen'
  Generating Code...
  libbz2.vcxproj -> C:\bzip2\Release\libbz2.lib
------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========

32bit

------ Build started: Project: ZERO_CHECK, Configuration: Release Win32 ------
  Checking Build System
  CMake does not need to re-run because C:/bzip2_32/CMakeFiles/generate.stamp is up-to-date.
------ Build started: Project: libbz2, Configuration: Release Win32 ------
  Building Custom Rule C:/Users/Michael/Documents/Git/bzip2/CMakeLists.txt
  CMake does not need to re-run because C:/bzip2_32/CMakeFiles/generate.stamp is up-to-date.
  blocksort.c
  huffman.c
  crctable.c
  randtable.c
  compress.c
  decompress.c
  bzlib.c
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1417): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1418): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1423): warning C4996: 'setmode': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _setmode. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\io.h(338) : see declaration of 'setmode'
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1423): warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fileno. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(718) : see declaration of 'fileno'
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1425): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(211) : see declaration of 'fopen'
C:\Users\Michael\Documents\Git\bzip2\bzlib.c(1431): warning C4996: 'fdopen': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fdopen. See online help for details.
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(716) : see declaration of 'fdopen'
  Generating Code...
  libbz2.vcxproj -> C:\bzip2_32\Release\libbz2.lib
------ Skipped Build: Project: ALL_BUILD, Configuration: Release Win32 ------
Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========

**Comment by jcfr** [comment]
Thanks for your help.

Slicer has been updated to integrate bzip2 library.

xref https://github.com/Slicer/Slicer/pull/745
